version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Entered the install phase...
      - echo Build started on `date`
      - pip3 install -r requirements.txt
      - python3 -m playwright install --with-deps
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pytest 
    finally:
      - echo This always runs even if the install command fails